version: '3'
    
services:      
  webApp.API:
    container_name: Styme.API
    image: styme-api
    build:
      context: .
      dockerfile: src/Styme.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
      - db.database      

  db.database:
    container_name: styme-db
    image: postgres
    restart: always
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senh@secret@123
      - POSTGRES_DB=styme-db
    volumes:
      - /home/docker/pgdata:/var/lib/postgresql/data
